### ISSUE TITLE
margaret not working to me

### ISSUE THREAD

**Issue by cesarmarinhorj** [sogaiu/margaret#1]
Install was perfect:
root@NBSS1:~# jpm install https://github.com/sogaiu/margaret
Repositório vazio Git inicializado em  /usr/local/lib/janet/.cache/git__https___github.com_sogaiu_margaret/.git/
remote: Enumerating objects: 1034, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 1034 (delta 19), reused 35 (delta 15), pack-reused 989
Receiving objects: 100% (1034/1034), 247.18 KiB | 703.00 KiB/s, done.
Resolving deltas: 100% (611/611), done.
From https://github.com/sogaiu/margaret
 * [new branch]      master     -> origin/master
From https://github.com/sogaiu/margaret
 * branch            HEAD       -> FETCH_HEAD
HEAD is now at c1e847f Update README
generating /usr/local/lib/janet/.manifests/margaret.jdn...
Installed as 'margaret'.
copying /usr/local/lib/janet/.cache/git__https___github.com_sogaiu_margaret/margaret to /usr/local/lib/janet...
root@NBSS1:~# 

but import dont works:
repl:1:> (import margaret)
error: could not find module margaret:
    /usr/local/lib/janet/margaret.jimage
    /usr/local/lib/janet/margaret.janet
    /usr/local/lib/janet/margaret/init.janet
    /usr/local/lib/janet/margaret.so
  in require-1 [boot.janet] on line 3038, column 20
  in import* [boot.janet] on line 3080, column 15
  in _thunk [repl] (tailcall) on line 1, column 1
repl:2:>

**Comment by sogaiu** [comment]
I think may be `(import margaret/meg)` might work better (see [here](https://github.com/sogaiu/margaret#usage)).

Does that help?

**Comment by sogaiu** [comment]
Going to close this issue for now, but feel free to re-open if there is more to discuss :)
